cargo-features = ["per-package-target"]

[package]
name = "booters_arch_x86_64_bios"
version = "0.1.0"
edition = "2021"
forced-target = "x86_64-unknown-none"

[[bin]]
name = "booters_x86_64_bios"
path = "src/main.rs"

[dependencies]
