[workspace]
members = ["src/boot_frame_core",
           "src/boot_frame_common",
           "src/arch/aarch64/boot_frame_arch_aarch64_mtk",
           "src/arch/x86/boot_frame_arch_x86_bios",
           "src/arch/x86_64/boot_frame_arch_x86_64_bios",
           "src/arch/x86_64/boot_frame_arch_x86_64_efi"]

[profile.dev]
lto = true
opt-level = 3
codegen-units = 1
debug = true
panic = "abort"

[profile.dev.package."*"]
codegen-units = 1
opt-level = 3
debug = true

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1
debug = false

[profile.release.package."*"]
codegen-units = 1
opt-level = 'z'
debug = false

