cargo-features = ["per-package-target"]

[package]
name = "booters_arch_aarch64_mtk"
version = "0.1.0"
edition = "2021"
forced-target = "aarch64-unknown-none"

[[bin]]
name = "booters_aarch64_mtk"
path = "src/main.rs"

[dependencies]

