cargo-features = ["per-package-target"]

[package]
name = "booters_arch_x86_bios"
version = "0.1.0"
edition = "2021"
forced-target = "i686-unknown-none.json"

[[bin]]
name = "booters_x86_bios"
path = "src/main.rs"

[dependencies]
